### ISSUE TITLE
Unable to login as Anonymous user

### ISSUE THREAD

**Issue by fungc-io** [authgear/authgear-demo-app-rn#31]
This error is shown when a tap "Continue as Guest"

![IMG_3696](https://uploads.linear.app/860e83ae-05f0-4c4b-bd93-8a4b8d251836/f9747dca-a598-4270-8d99-acb056ac5c08/7e26cef1-d622-4481-be1b-1308e50804ae?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzg2MGU4M2FlLTA1ZjAtNGM0Yi1iZDkzLThhNGI4ZDI1MTgzNi9mOTc0N2RjYS1hNTk4LTQyNzAtOGQ5OS1hY2IwNTZhYzVjMDgvN2UyNmNlZjEtZDYyMi00NDgxLWJlMWItMTMwOGU1MDgwNGFlIiwiaWF0IjoxNzE2OTcyMzY4LCJleHAiOjMzMjg3NTMyMzY4fQ.XLdAzuny7wTW2rp5OCNOM5OhHvT8JBlme8DCoeXIQWA)

**Comment by louischan-oursky** [comment]
[https://github.com/authgear/authgear-demo-app-rn/commit/a044af02821f24d1879c072a31b48083c3d71c7b](https://github.com/authgear/authgear-demo-app-rn/commit/a044af02821f24d1879c072a31b48083c3d71c7b)
